### ISSUE TITLE
Compare multiple runs

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#277]
```[tasklist]
### Tasks
- [ ] https://github.com/IN-CORE/incore-playbook/issues/289
- [ ] https://github.com/IN-CORE/incore-playbook/issues/290
- [ ] https://github.com/IN-CORE/incore-playbook/issues/288
- [ ] https://github.com/IN-CORE/incore-playbook/issues/307
- [ ] https://github.com/IN-CORE/incore-playbook/issues/308
- [ ] https://github.com/IN-CORE/incore-playbook/issues/291
- [ ] https://github.com/IN-CORE/incore-playbook/issues/292
- [ ] https://github.com/IN-CORE/incore-playbook/issues/298
- [ ] https://github.com/IN-CORE/incore-playbook/issues/305
- [ ] https://github.com/IN-CORE/incore-playbook/issues/317
- [ ] https://github.com/IN-CORE/incore-playbook/issues/320
- [ ] https://github.com/IN-CORE/incore-playbook/issues/322
```

----

Mockup Link:
https://docs.google.com/presentation/d/1e0tCELOKhv41ZQZodgfcSk4uZPGsoZHB9p4JlqQBUx0/edit#slide=id.g268c7860071_0_1

------

Updated Notes based on discussion:

Run without retrofit and run with retrofit and compare all metrics. E.g.
![Image](https://github.com/IN-CORE/incore-playbook/assets/13950475/61dd7602-cae7-4e3b-91b2-265586c76ea1)

### Trigger the run
Have checkbox right next to each run; select 2 and click compare button

### Condense approach 

Table: 
- Use the shared column header don't list them twice
- Append rows 
- Calculate the differences

Map 
task see https://github.com/IN-CORE/incore-playbook/issues/288
- Syncing Map zoom and scroll. Example see: https://openlayers.org/en/latest/examples/side-by-side.html
- Need to investigate if it works for the layer switcher 

Charts
- CGE bar chart only needs to append one additional bar for the (after event). The Before event is the same
- HHRS bar chart just have two sets
- Building damage bar chart. One option could be limit by each damage state. Need to come up with a mockup

-----

An interface to compare multiple executions to see the differences:
e.g. with different retrofit strategies, different hazards, how would it affect damage results, dislocation, etc

2 (or N) Interface side by side? 
One table/map but display differences (-xxx, +xxx, etc)?

**Comment by longshuicy** [comment]
Open the comparison in new page.
