### ISSUE TITLE
Release incore-playbook 0.6.0 and update config for each city playbooks

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#337]
TODOs:

```[tasklist]
### Tasks
- [x] Release 0.6.0
- [x] Update SLC and Galveston package json version
- [x] Update SLC and Galveston datawolf and global config to allow retrofit related change
- [x] Update SLC and Galveston map related config if applies
- [x] Helm repo and box folder
- [x] Deploy
- [x] Meet with Leigh for instruction on design critique
```
