### ISSUE TITLE
Release incore-playbook 0.6.1 and update config for each city playbooks

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#387]
0.6.1 should have:
- RS builder
- RS summary
- Comparison interface improved
- Bugfixes

```[tasklist]
### Tasks
- [ ] Release 0.6.1 core incore-playbook
- [ ] Update SLC and Galveston package json version
- [ ] Update SLC and Galveston datawolf and global config to allow retrofit related change
- [ ] Helm repo and box folder
- [ ] Deploy
```
